import { Product } from './store';

export const products: Product[] = [
  {
    id: '1',
    name: 'Support Ordinateur Portable Ergonomique',
    price: 34.99,
    originalPrice: 44.99,
    image: '/support-ordi-main.jpg',
    images: ['/support-ordi-main.jpg', '/support-1.jpg', '/support-2.jpg', '/support-3.jpg', '/support-4.jpg', '/support-5.jpg'],
    category: 'Supports',
    model: 'Universel (PC & Mac)',
    rating: 4.9,
    reviewCount: 128,
    description: 'Support pour ordinateur portable ultra-léger et pliable. Améliore la posture de travail et garanti une dissipation thermique optimale grâce à son excellente ventilation aérienne.',
    features: [
      'Hauteur et angle ajustables (Ergonomie)',
      'Design ultra-compact et pliable (220g)',
      'Aération maximale (Air Flow Ventilation)',
      'Pieds antidérapants en silicone',
      'Pochette de transport incluse',
    ],
    colors: ['#1a1a1a', '#e5e5e5'],
    badge: 'Nouveau',
    inStock: true,
  },
  {
    id: '2',
    name: 'Support Téléphone Acier',
    price: 29.99,
    originalPrice: 39.99,
    image: '/support-phone-main.jpg', 
    images: ['/support-phone-main.jpg', '/support-phone-1.jpg', '/support-phone-2.jpg', '/support-phone-3.jpg', '/support-phone-4.jpg', '/support-phone-5.jpg'],
    category: 'Supports',
    model: 'Universel (Smartphones)',
    rating: 4.8,
    reviewCount: 112,
    description: 'Support de bureau en acier robuste avec base rotative à 360°. Design pliable et ergonomique pour un angle de vue parfait à tout moment.',
    features: [
      'Rotation fluide à 360° de la base',
      'Construction en acier massif de haute qualité',
      'Double axe avec ajustement multi-angles',
      'Coussinets en silicone anti-rayures et antidérapants',
      'Design pliable facile à transporter',
    ],
    colors: ['#806b9b'],
    badge: 'Tendance',
    inStock: true,
  },
  {
    id: '3',
    name: 'Câble Tressé Kevlar (USB-C & Lightning)',
    price: 24.99,
    originalPrice: 29.99,
    image: '/cable-1.png', 
    images: ['/cable-1.png', '/cable-2.png', '/cable-3.png'],
    category: 'Câbles',
    model: 'USB-C vers USB-C / Lightning',
    rating: 4.7,
    reviewCount: 204,
    description: 'Câble de charge premium floqué NestCase, renforcé avec de la fibre de Kevlar.',
    features: [
      'Double tresse en nylon balistique',
      'Renforcement en Kevlar interieur',
      'Testé à plus de 25 000 pliures',
      'Support power delivery (PD)',
      'Embout en alliage d\'aluminium',
    ],
    colors: ['#1a1a1a', '#6366f1'],
    inStock: false,
  },
  {
    id: '4',
    name: 'Coque Édition Signature',
    price: 49.99,
    originalPrice: 59.99,
    image: '/case-carbon-navy.png',
    images: ['/case-carbon-navy.png', '/case-geometric-black.png'],
    category: 'Coques',
    model: 'iPhone 15 / Galaxy S24',
    rating: 4.8,
    reviewCount: 456,
    description: 'Notre coque iconique. Protection militaire MIL-STD-810G, compatible MagSafe.',
    features: [
      'Protection antichoc jusqu\'à 3m',
      'MagSafe ultra-puissant (N52)',
      'Fibre de carbone / Polycarbonate',
      'Bords surélevés caméra & écran',
      'Boutons tactiles premium',
    ],
    colors: ['#0f172a', '#1e3a5f', '#1a1a1a'],
    badge: 'Best-Seller',
    inStock: false,
  }
];

export const categories = ['Tous', 'Supports', 'Câbles', 'Coques'];
export const models = ['Tous', 'Universel (PC & Mac)', 'Universel (Smartphones)', 'USB-C vers USB-C / Lightning', 'iPhone 15 / Galaxy S24'];
export const sortOptions = [
  { value: 'featured', label: 'Mis en avant' },
  { value: 'price-asc', label: 'Prix croissant' },
  { value: 'price-desc', label: 'Prix décroissant' },
  { value: 'rating', label: 'Mieux notés' },
  { value: 'newest', label: 'Nouveautés' },
];
